// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { randomLogNormal, randomNormal } from 'd3-random';

export interface DistributionItem {
  id: string;
  fn: any;
  isActive: boolean;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  distributions = [
    { 'id': 'normal', fn: randomNormal(.5, 1), isActive: true },
    { 'id': 'log-normal', fn: randomLogNormal(.5, 1), isActive: false }
  ];

  onDistributionChange = dist => {
    this.distributions = this.distributions.map(d => {
      return {
        ...d,
        isActive: d.id === dist.id
      }
    })
  };

  get activeDistribution(): any {
    return this.distributions.find(d => d.isActive);
  }
}

<div class="App">
  <div class="Header">
    <button *ngFor="let distribution of distributions"
            [ngClass]="distribution.isActive ? 'active' : ''"
            (click)="onDistributionChange(distribution)">
      {{distribution.id}}
    </button>
  </div>
  <app-visualization [selectedDistribution]="activeDistribution">
  </app-visualization>
</div>

// react-app/src/components/App/index.js
import React, {useState} from 'react';
import Visualization from "./Visualization";
import {randomLogNormal, randomNormal} from "d3-random";

function App() {
    const [distributions, setDistributions] = useState([
        {'id': 'normal', fn: randomNormal(.5, 1), isActive: true},
        {'id': 'log-normal', fn: randomLogNormal(.5, 1), isActive: false}
    ]);

    const onDistributionChange = dist => evt => setDistributions(distributions.map(d => {
        return {
            ...d,
            isActive: d.id === dist.id
        }
    }));
    return (
        <div className="App">
            <div className="Header">
                {
                    distributions.map(distribution => {
                        return (
                            <button key={`button-for-${distribution.id}`}
                                    className={distribution.isActive ? 'active' : ''}
                                    onClick={onDistributionChange(distribution)}>
                                {distribution.id}
                            </button>
                        )
                    })
                }
            </div>
            <Visualization selectedDistribution={distributions.find(d => d.isActive)}/>
        </div>
    );
}

export default App;
