// react-app/src/components/App/Visualization/index.js
import React from 'react';
import Axes from "./Axes";
import {calculateLayout, useDimensions} from "../../../utils";
import Marker from "./Marker";
import {scaleLinear} from "d3-scale";
import {extent, range} from "d3-array";

const Visualization = ({selectedDistribution}) => {

    // Retrieve the width and height of the parent element and set up some constant variables
    const [chartRef, {width, height}] = useDimensions({width: 900, height: 600});
    const margin = {
        left: 40,
        right: 40,
        bottom: 40,
        top: 40
    };
    const markerRadius = 7.5;

    // Assign helpers for retrieving x data point
    const xAccessor = d => d.x;

    // Retrieve the inner height and width for which we will be drawing on
    const innerHeight = height - margin.top - margin.bottom;
    const innerWidth = width - margin.left - margin.right;

    // Create a random sampling of data points
    const data = range(250).map(d => {
        return {
            x: selectedDistribution.fn(),
            y: innerHeight / 2,
            r: markerRadius,
            id: `marker-${d}`
        }
    }, .1);

    // Use the data points to calculate the scales
    const xScale = scaleLinear()
        .range([0, innerWidth])
        .domain(extent(data, xAccessor));

    // Use a force simulation to place the markers throughout the visualization
    const items = calculateLayout(data.map(d => {
        return {
            ...d,
            x: xScale(xAccessor(d)),
            fx: xScale(xAccessor(d)), // fix the x-position for the markers
        }
    }));

    return (
        <svg width={width} height={height} ref={chartRef}>
            <g transform={`translate(${margin.left},${margin.top})`}>
                {
                    items.map(d => {
                        return (<Marker key={`marker-for-${d.id}`} item={d}/>)
                    })
                }
                <Axes height={innerHeight} xScale={xScale}/>
            </g>
        </svg>
    )
};
export default Visualization;

// angular-app/src/app/visualization/visualization.component.ts
import { ChangeDetectorRef, Component, ElementRef, HostListener, Input, OnChanges, OnInit } from '@angular/core';
import { Subject } from 'rxjs';
import { throttleTime } from 'rxjs/operators';
import { AxesItem } from './axes/axes.component';
import { range, extent } from 'd3-array';
import { scaleLinear } from 'd3-scale';
import { MarkerItem } from './marker/marker.component';
import { DistributionItem } from '../app.component';
import { calculateLayout } from "../../lib/util";

@Component({
  selector: 'app-visualization',
  templateUrl: './visualization.component.html'
})
export class VisualizationComponent implements OnInit, OnChanges {
  @Input() selectedDistribution: DistributionItem;
  xScale = scaleLinear();
  margin = {
    left: 40,
    right: 40,
    bottom: 40,
    top: 40
  };
  markerRadius = 7.5;
  xAccessor = d => d.x;
  data: any[];
  elementId = '.Visualization';
  changeSize = new Subject();

  @HostListener('window:resize', ['$event.target'])
  public onResize() {
    this.changeSize.next();
  }

  constructor(protected element: ElementRef, private cdr: ChangeDetectorRef) {
  }

  get height(): number {
    return this.element.nativeElement.querySelector(this.elementId).offsetHeight;
  }

  get width(): number {
    return this.element.nativeElement.querySelector(this.elementId).offsetWidth;
  }

  get innerHeight(): number {
    return this.height - this.margin.top - this.margin.bottom;
  }

  get innerWidth(): number {
    return this.width - this.margin.left - this.margin.right;
  }

  ngOnInit(): void {
    this.changeSize
      .asObservable()
      .pipe(
        throttleTime(250)
      )
      .subscribe(() => this.setAxisScales());
    this.draw();
  }

  updateData() {

    this.data = range(250).map(d => {
      return {
        x: this.selectedDistribution.fn(),
        y: this.innerHeight / 2,
        r: this.markerRadius,
        id: `marker-${d}`
      }
    });
    this.setAxisScales();
    this.data = calculateLayout(this.data.map(d => {
      return {
        ...d,
        x: this.xScale(this.xAccessor(d)),
        fx: this.xScale(this.xAccessor(d)), // fix the x-position for the markers
      }
    }));
  }

  setAxisScales() {
    this.xScale
      .range([0, this.innerWidth])
      .domain(extent(this.data, this.xAccessor));
  }

  get gTransform(): string {
    return `translate(${this.margin.left},${this.margin.top})`;
  }

  formatAxes(): AxesItem {
    return {
      xScale: this.xScale,
      height: this.innerHeight
    };
  }

  formatMarkerItem(row): MarkerItem {
    return {
      x: row.x,
      y: row.y,
      r: row.r
    }
  }

  protected trackByPoint(item) {
    return item.id;
  }

  private draw() {
    this.updateData();
    this.cdr.detectChanges();
  }

  ngOnChanges() {
    setTimeout(() => {
      this.draw();
    }, 0);
  }
}

<div class="Visualization">
  <svg [attr.width.px]="width" [attr.height.px]="height">
    <g attr.transform="{{gTransform}}">
      <g app-marker
         *ngFor="let row of data; trackBy: trackByPoint"
         [item]="formatMarkerItem(row)">
      </g>
      <g app-axes [item]="formatAxes()"></g>
    </g>
  </svg>
</div>
