// angular-app/src/app/visualization/axes/axes.component.ts
import { Component, ElementRef, Input, NgZone, OnChanges, OnInit, ViewChild } from '@angular/core';
import { select } from 'd3-selection';
import { axisBottom } from 'd3-axis';

export interface AxesItem {
  xScale: any;
  height: number;
}

@Component({
  selector: '[app-axes]',
  templateUrl: './axes.component.html'
})
export class AxesComponent implements OnInit, OnChanges {
  @Input() item: AxesItem;
  @ViewChild('xAxisEl', { static: true }) xAxisEl: ElementRef;

  constructor(private zone: NgZone) {
  }

  renderXAxis(): void {
    const xAxis = select(this.xAxisEl.nativeElement);

    this.zone.runOutsideAngular(() => {
      xAxis
        .call(axisBottom(this.item.xScale));
    });
  }

  renderAxes(): void {
    this.renderXAxis();
  }

  ngOnChanges() {
    this.renderAxes();
  }

  ngOnInit() {
    this.renderAxes();
  }

  get xAxisTransform(): string {
    return `translate(0, ${this.item.height})`;
  }
}

<svg:g class="axes">
  <svg:g #xAxisEl class="x axis" attr.transform="{{xAxisTransform}}"></svg:g>
</svg:g>

// react-app/src/components/App/Visualization/Axes/index.js
import React, {useEffect, useRef} from 'react';
import {select} from 'd3-selection';
import {axisBottom} from "d3-axis";

const Axes = ({xScale, height}) => {
    const xAxisRef = useRef();

    useEffect(() => {
        renderAxes();
    });

    const renderAxes = () => {
        renderXAxis();
    };

    const renderXAxis = () => {
        const xAxis = select(xAxisRef.current);
        xAxis.call(axisBottom(xScale));
    };

    return (
        <g className="axes">
            <g className="x axis" ref={xAxisRef} transform={`translate(0,${height})`}/>
        </g>
    );
};
export default Axes;
