// react-app/src/components/App/Visualization/Marker/index.js
import React, {useEffect, useRef} from 'react';
import 'd3-transition';
import {select} from 'd3-selection';

const Marker = ({item}) => {
    const markerRef = useRef();

    useEffect(() => {
        select(markerRef.current)
            .transition()
            .duration(1000)
            .attr('cx', item.x)
            .attr('cy', item.y);
    }, [item]);

    return (
        <circle ref={markerRef} r={item.r} className='marker'/>
    );
};
export default Marker;

// angular-app/src/app/visualization/marker/marker.component.ts
import { Component, Input } from '@angular/core';

export interface MarkerItem {
  x: number;
  y: number;
  r: number;
}

@Component({
  selector: '[app-marker]',
  templateUrl: './marker.component.html'
})
export class MarkerComponent {
  @Input() item: MarkerItem;
  protected transition = t => t.duration(1000);
}

<svg:circle [attr.r.px]="item.r"
            [ngClass]="'marker'"
            [appSvgTransition]="transition"
            [d3-attr]="{cx: item.x, cy: item.y}">
</svg:circle>
